name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Log in to Docker Hub
    #   if: env.ACT != 'true'
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        no-cache: true
        platforms: linux/amd64, linux/arm64
        file: ./Dockerfile
        tags: |
          bunapp:latest
          bunapp:1.0
        labels: |
          maintainer=peter@dailybugle.com
          version=1.0


    # - name: Build and push
    #   uses: docker/bake-action@v4
    #   with:
    #     push: true
